---
http_interactions:
- request:
    method: post
    uri: http://10.0.5.5:4243/containers/create
    body:
      encoding: UTF-8
      string: ! '{"Hostname":"test-container","User":"test","Memory":33554432,"MemorySwap":67108864,"CpuShares":1,"AttachStdin":false,"AttachStdout":true,"AttachStderr":true,"PortSpecs":["80","443"],"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PORT=5000","ENVIRONTMENT=production"],"Dns":null,"Volumes":{"/var/lib/app":{}},"VolumesFrom":"","Cmd":["echo","hello
        world"],"Image":"base"}'
    headers:
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: !binary |-
        Q3JlYXRlZA==
    headers:
      !binary "RGF0ZQ==":
      - !binary |-
        RnJpLCAyNCBNYXkgMjAxMyAxNToyODozNCBHTVQ=
      !binary "VHJhbnNmZXItRW5jb2Rpbmc=":
      - !binary |-
        Y2h1bmtlZA==
      !binary "Q29udGVudC1UeXBl":
      - !binary |-
        dGV4dC9wbGFpbjsgY2hhcnNldD11dGYtOA==
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        eyJJZCI6ImJhNTY3MGEyY2VkMiIsIldhcm5pbmdzIjpbIllvdXIga2VybmVs
        IGRvZXMgbm90IHN1cHBvcnQgbWVtb3J5IHN3YXAgY2FwYWJpbGl0aWVzLiBM
        aW1pdGF0aW9uIGRpc2NhcmRlZC4iXX0=
    http_version: 
  recorded_at: Fri, 24 May 2013 15:28:34 GMT
- request:
    method: delete
    uri: http://10.0.5.5:4243/containers/ba5670a2ced2?v=true
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
  response:
    status:
      code: 204
      message: !binary |-
        Tm8gQ29udGVudA==
    headers:
      !binary "RGF0ZQ==":
      - !binary |-
        RnJpLCAyNCBNYXkgMjAxMyAxNToyODozNCBHTVQ=
      !binary "VHJhbnNmZXItRW5jb2Rpbmc=":
      - !binary |-
        Y2h1bmtlZA==
      !binary "Q29udGVudC1UeXBl":
      - !binary |-
        dGV4dC9wbGFpbjsgY2hhcnNldD11dGYtOA==
    body:
      encoding: ASCII-8BIT
      string: !binary ""
    http_version: 
  recorded_at: Fri, 24 May 2013 15:28:34 GMT
recorded_with: VCR 2.5.0
